// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: DistSSE.proto

#include "DistSSE.pb.h"
#include "DistSSE.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace DistSSE {

static const char* RPC_method_names[] = {
  "/DistSSE.RPC/setup",
  "/DistSSE.RPC/search",
  "/DistSSE.RPC/update",
  "/DistSSE.RPC/batch_update",
  "/DistSSE.RPC/cache",
  "/DistSSE.RPC/batch_cache",
  "/DistSSE.RPC/ReProof",
};

std::unique_ptr< RPC::Stub> RPC::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RPC::Stub> stub(new RPC::Stub(channel, options));
  return stub;
}

RPC::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_setup_(RPC_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_search_(RPC_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_update_(RPC_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_batch_update_(RPC_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_cache_(RPC_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_batch_cache_(RPC_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_ReProof_(RPC_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RPC::Stub::setup(::grpc::ClientContext* context, const ::DistSSE::SetupRequestMessage& request, ::DistSSE::ExecuteStatus* response) {
  return ::grpc::internal::BlockingUnaryCall< ::DistSSE::SetupRequestMessage, ::DistSSE::ExecuteStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setup_, context, request, response);
}

void RPC::Stub::async::setup(::grpc::ClientContext* context, const ::DistSSE::SetupRequestMessage* request, ::DistSSE::ExecuteStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::DistSSE::SetupRequestMessage, ::DistSSE::ExecuteStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setup_, context, request, response, std::move(f));
}

void RPC::Stub::async::setup(::grpc::ClientContext* context, const ::DistSSE::SetupRequestMessage* request, ::DistSSE::ExecuteStatus* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setup_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::DistSSE::ExecuteStatus>* RPC::Stub::PrepareAsyncsetupRaw(::grpc::ClientContext* context, const ::DistSSE::SetupRequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::DistSSE::ExecuteStatus, ::DistSSE::SetupRequestMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setup_, context, request);
}

::grpc::ClientAsyncResponseReader< ::DistSSE::ExecuteStatus>* RPC::Stub::AsyncsetupRaw(::grpc::ClientContext* context, const ::DistSSE::SetupRequestMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetupRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::DistSSE::SearchReply>* RPC::Stub::searchRaw(::grpc::ClientContext* context, const ::DistSSE::SearchRequestMessage& request) {
  return ::grpc::internal::ClientReaderFactory< ::DistSSE::SearchReply>::Create(channel_.get(), rpcmethod_search_, context, request);
}

void RPC::Stub::async::search(::grpc::ClientContext* context, const ::DistSSE::SearchRequestMessage* request, ::grpc::ClientReadReactor< ::DistSSE::SearchReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::DistSSE::SearchReply>::Create(stub_->channel_.get(), stub_->rpcmethod_search_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::DistSSE::SearchReply>* RPC::Stub::AsyncsearchRaw(::grpc::ClientContext* context, const ::DistSSE::SearchRequestMessage& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::DistSSE::SearchReply>::Create(channel_.get(), cq, rpcmethod_search_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::DistSSE::SearchReply>* RPC::Stub::PrepareAsyncsearchRaw(::grpc::ClientContext* context, const ::DistSSE::SearchRequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::DistSSE::SearchReply>::Create(channel_.get(), cq, rpcmethod_search_, context, request, false, nullptr);
}

::grpc::Status RPC::Stub::update(::grpc::ClientContext* context, const ::DistSSE::UpdateRequestMessage& request, ::DistSSE::ExecuteStatus* response) {
  return ::grpc::internal::BlockingUnaryCall< ::DistSSE::UpdateRequestMessage, ::DistSSE::ExecuteStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_update_, context, request, response);
}

void RPC::Stub::async::update(::grpc::ClientContext* context, const ::DistSSE::UpdateRequestMessage* request, ::DistSSE::ExecuteStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::DistSSE::UpdateRequestMessage, ::DistSSE::ExecuteStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_update_, context, request, response, std::move(f));
}

void RPC::Stub::async::update(::grpc::ClientContext* context, const ::DistSSE::UpdateRequestMessage* request, ::DistSSE::ExecuteStatus* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_update_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::DistSSE::ExecuteStatus>* RPC::Stub::PrepareAsyncupdateRaw(::grpc::ClientContext* context, const ::DistSSE::UpdateRequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::DistSSE::ExecuteStatus, ::DistSSE::UpdateRequestMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_update_, context, request);
}

::grpc::ClientAsyncResponseReader< ::DistSSE::ExecuteStatus>* RPC::Stub::AsyncupdateRaw(::grpc::ClientContext* context, const ::DistSSE::UpdateRequestMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncupdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::DistSSE::UpdateRequestMessage>* RPC::Stub::batch_updateRaw(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response) {
  return ::grpc::internal::ClientWriterFactory< ::DistSSE::UpdateRequestMessage>::Create(channel_.get(), rpcmethod_batch_update_, context, response);
}

void RPC::Stub::async::batch_update(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response, ::grpc::ClientWriteReactor< ::DistSSE::UpdateRequestMessage>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::DistSSE::UpdateRequestMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_batch_update_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::DistSSE::UpdateRequestMessage>* RPC::Stub::Asyncbatch_updateRaw(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::DistSSE::UpdateRequestMessage>::Create(channel_.get(), cq, rpcmethod_batch_update_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::DistSSE::UpdateRequestMessage>* RPC::Stub::PrepareAsyncbatch_updateRaw(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::DistSSE::UpdateRequestMessage>::Create(channel_.get(), cq, rpcmethod_batch_update_, context, response, false, nullptr);
}

::grpc::Status RPC::Stub::cache(::grpc::ClientContext* context, const ::DistSSE::CacheRequestMessage& request, ::DistSSE::ExecuteStatus* response) {
  return ::grpc::internal::BlockingUnaryCall< ::DistSSE::CacheRequestMessage, ::DistSSE::ExecuteStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_cache_, context, request, response);
}

void RPC::Stub::async::cache(::grpc::ClientContext* context, const ::DistSSE::CacheRequestMessage* request, ::DistSSE::ExecuteStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::DistSSE::CacheRequestMessage, ::DistSSE::ExecuteStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_cache_, context, request, response, std::move(f));
}

void RPC::Stub::async::cache(::grpc::ClientContext* context, const ::DistSSE::CacheRequestMessage* request, ::DistSSE::ExecuteStatus* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_cache_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::DistSSE::ExecuteStatus>* RPC::Stub::PrepareAsynccacheRaw(::grpc::ClientContext* context, const ::DistSSE::CacheRequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::DistSSE::ExecuteStatus, ::DistSSE::CacheRequestMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_cache_, context, request);
}

::grpc::ClientAsyncResponseReader< ::DistSSE::ExecuteStatus>* RPC::Stub::AsynccacheRaw(::grpc::ClientContext* context, const ::DistSSE::CacheRequestMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccacheRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::DistSSE::CacheRequestMessage>* RPC::Stub::batch_cacheRaw(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response) {
  return ::grpc::internal::ClientWriterFactory< ::DistSSE::CacheRequestMessage>::Create(channel_.get(), rpcmethod_batch_cache_, context, response);
}

void RPC::Stub::async::batch_cache(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response, ::grpc::ClientWriteReactor< ::DistSSE::CacheRequestMessage>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::DistSSE::CacheRequestMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_batch_cache_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::DistSSE::CacheRequestMessage>* RPC::Stub::Asyncbatch_cacheRaw(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::DistSSE::CacheRequestMessage>::Create(channel_.get(), cq, rpcmethod_batch_cache_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::DistSSE::CacheRequestMessage>* RPC::Stub::PrepareAsyncbatch_cacheRaw(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::DistSSE::CacheRequestMessage>::Create(channel_.get(), cq, rpcmethod_batch_cache_, context, response, false, nullptr);
}

::grpc::Status RPC::Stub::ReProof(::grpc::ClientContext* context, const ::DistSSE::ReProofRequestMessage& request, ::DistSSE::ExecuteStatus* response) {
  return ::grpc::internal::BlockingUnaryCall< ::DistSSE::ReProofRequestMessage, ::DistSSE::ExecuteStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReProof_, context, request, response);
}

void RPC::Stub::async::ReProof(::grpc::ClientContext* context, const ::DistSSE::ReProofRequestMessage* request, ::DistSSE::ExecuteStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::DistSSE::ReProofRequestMessage, ::DistSSE::ExecuteStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReProof_, context, request, response, std::move(f));
}

void RPC::Stub::async::ReProof(::grpc::ClientContext* context, const ::DistSSE::ReProofRequestMessage* request, ::DistSSE::ExecuteStatus* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReProof_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::DistSSE::ExecuteStatus>* RPC::Stub::PrepareAsyncReProofRaw(::grpc::ClientContext* context, const ::DistSSE::ReProofRequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::DistSSE::ExecuteStatus, ::DistSSE::ReProofRequestMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReProof_, context, request);
}

::grpc::ClientAsyncResponseReader< ::DistSSE::ExecuteStatus>* RPC::Stub::AsyncReProofRaw(::grpc::ClientContext* context, const ::DistSSE::ReProofRequestMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReProofRaw(context, request, cq);
  result->StartCall();
  return result;
}

RPC::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPC_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RPC::Service, ::DistSSE::SetupRequestMessage, ::DistSSE::ExecuteStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RPC::Service* service,
             ::grpc::ServerContext* ctx,
             const ::DistSSE::SetupRequestMessage* req,
             ::DistSSE::ExecuteStatus* resp) {
               return service->setup(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPC_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< RPC::Service, ::DistSSE::SearchRequestMessage, ::DistSSE::SearchReply>(
          [](RPC::Service* service,
             ::grpc::ServerContext* ctx,
             const ::DistSSE::SearchRequestMessage* req,
             ::grpc::ServerWriter<::DistSSE::SearchReply>* writer) {
               return service->search(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPC_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RPC::Service, ::DistSSE::UpdateRequestMessage, ::DistSSE::ExecuteStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RPC::Service* service,
             ::grpc::ServerContext* ctx,
             const ::DistSSE::UpdateRequestMessage* req,
             ::DistSSE::ExecuteStatus* resp) {
               return service->update(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPC_method_names[3],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< RPC::Service, ::DistSSE::UpdateRequestMessage, ::DistSSE::ExecuteStatus>(
          [](RPC::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::DistSSE::UpdateRequestMessage>* reader,
             ::DistSSE::ExecuteStatus* resp) {
               return service->batch_update(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPC_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RPC::Service, ::DistSSE::CacheRequestMessage, ::DistSSE::ExecuteStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RPC::Service* service,
             ::grpc::ServerContext* ctx,
             const ::DistSSE::CacheRequestMessage* req,
             ::DistSSE::ExecuteStatus* resp) {
               return service->cache(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPC_method_names[5],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< RPC::Service, ::DistSSE::CacheRequestMessage, ::DistSSE::ExecuteStatus>(
          [](RPC::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::DistSSE::CacheRequestMessage>* reader,
             ::DistSSE::ExecuteStatus* resp) {
               return service->batch_cache(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPC_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RPC::Service, ::DistSSE::ReProofRequestMessage, ::DistSSE::ExecuteStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RPC::Service* service,
             ::grpc::ServerContext* ctx,
             const ::DistSSE::ReProofRequestMessage* req,
             ::DistSSE::ExecuteStatus* resp) {
               return service->ReProof(ctx, req, resp);
             }, this)));
}

RPC::Service::~Service() {
}

::grpc::Status RPC::Service::setup(::grpc::ServerContext* context, const ::DistSSE::SetupRequestMessage* request, ::DistSSE::ExecuteStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RPC::Service::search(::grpc::ServerContext* context, const ::DistSSE::SearchRequestMessage* request, ::grpc::ServerWriter< ::DistSSE::SearchReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RPC::Service::update(::grpc::ServerContext* context, const ::DistSSE::UpdateRequestMessage* request, ::DistSSE::ExecuteStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RPC::Service::batch_update(::grpc::ServerContext* context, ::grpc::ServerReader< ::DistSSE::UpdateRequestMessage>* reader, ::DistSSE::ExecuteStatus* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RPC::Service::cache(::grpc::ServerContext* context, const ::DistSSE::CacheRequestMessage* request, ::DistSSE::ExecuteStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RPC::Service::batch_cache(::grpc::ServerContext* context, ::grpc::ServerReader< ::DistSSE::CacheRequestMessage>* reader, ::DistSSE::ExecuteStatus* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RPC::Service::ReProof(::grpc::ServerContext* context, const ::DistSSE::ReProofRequestMessage* request, ::DistSSE::ExecuteStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace DistSSE

